# Generated by Django 2.0.4 on 2018-04-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owolabiscrumy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstatus',
            name='scrumygoals',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='owolabiscrumy.GoalStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('WT', 'Weekly Task'), ('DT', 'Daily Task'), ('V', 'Verified'), ('D', 'Done')], default='DT', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='descriptions',
            field=models.TextField(default='Describe your goals here'),
        ),
    ]
