# Generated by Django 2.0.4 on 2018-04-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owolabiscrumy', '0002_auto_20180421_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('WT', 'Weekly Task'), ('DT', 'Daily Task'), ('V', 'Verified'), ('D', 'Done')], default='WT', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='descriptions',
            field=models.TextField(default='Describe your goals'),
        ),
    ]
