# Generated by Django 2.0.4 on 2018-04-22 22:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owolabiscrumy', '0004_auto_20180421_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='user',
            new_name='scrumyuser',
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='scrumyuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='owolabiscrumy.ScrumyUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
