# Generated by Django 2.0.4 on 2018-04-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owolabiscrumy', '0005_auto_20180422_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_type',
            field=models.CharField(choices=[('WG', 'Weekly Goal'), ('DT', 'Daily Task')], default='DT', max_length=2),
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='role',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('Q', 'Quality Analyst'), ('D', 'Developer')], default='O', max_length=1),
        ),
    ]
