# Generated by Django 2.0.4 on 2018-04-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owolabiscrumy', '0006_auto_20180423_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('V', 'Verified'), ('D', 'Done')], default='WT', max_length=50),
        ),
    ]
